application: talent-revolution-live
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: F4

libraries:
- name: ssl
  version: latest
- name: lxml
  version: latest
- name: PIL
  version: latest

builtins:
- appstats: on
- remote_api: on

handlers:

- url: /_ah/(mapreduce|queue|warmup).*
  script: core.wsgi.application
  login: admin
  secure: always

- url: /static/admin
  static_dir: static/dist/admin
  secure: always

- url: /static
  static_dir: static/dist
  secure: always
  http_headers:
    Access-Control-Allow-Origin: https://google.qualtrics.com

- url: /api/.*
  script: core.wsgi.application
  secure: always
  login: optional

# Set Django admin to be login:admin
- url: /admin.*
  script: core.wsgi.application
  secure: always
  login: admin

- url: /favicon\.ico
  static_files: static/dist/img/favicon.ico
  upload: static/dist/img/favicon\.ico

- url: /.*
  script: core.wsgi.application
  secure: always
  login: admin

skip_files:
    - manage.py
    - README.md
    - install_deps
    - requirements.txt
    - sitepackages/google_appengine*
    - (.*)\.scss
    - \.storage.*
    - (.*)\.pyc
    - (.*)\.scss

