application: gweb-digitalmaturity-staging
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: F4

libraries:
- name: ssl
  version: 2.7.11
- name: lxml
  version: latest
- name: PIL
  version: latest
- name: numpy
  version: "1.6.1"

builtins:
- appstats: on
- remote_api: on

handlers:

- url: /_ah/(mapreduce|queue|warmup).*
  script: core.wsgi.application
  login: admin
  secure: always

- url: /static/admin
  static_dir: static/dist/admin
  secure: always

- url: /static
  static_dir: static/dist
  secure: always
  login: optional
  http_headers:
    Access-Control-Allow-Origin: https://google.qualtrics.com

- url: /api/.*
  script: core.wsgi.application
  secure: always
  login: optional

# Set Django admin to be login:admin
- url: /admin.*
  script: core.wsgi.application
  secure: always
  login: admin

- url: /favicon\.png
  static_files: static/dist/img/favicon.png
  upload: static/dist/img/favicon\.png


# Only used on development
- url: /src/static/
  static_dir: static/
  secure: always

- url: /node_modules/
  static_dir: node_modules/
  secure: always

- url: /.*
  script: core.wsgi.application
  secure: always

  login: admin

skip_files:
    - manage.py
    - README.md
    - install_deps
    - requirements.txt
    - sitepackages/google_appengine*
    - (.*)\.scss
    - \.storage.*
    - (.*)\.pyc
    - (.*)\.scss
    - (.*)\.DS_Store
    - node_modules
    - src/node_modules
    - src/static/dev
    - src/static/src
